parameters:
    scribe.file_uploader.class:         Scribe\FileUploaderBundle\Services\FileUploader
    scribe.file_uploader_manager.class: Scribe\FileUploaderBundle\Services\FileManager
    scribe.file_uploader.twig.class:    Scribe\FileUploaderBundle\Templating\Extension\UploaderFileExtension

services:
    scribe.file_uploader:
        class: %scribe.file_uploader.class%
        arguments: ["@service_container"]
        scope: request

    scribe.file_uploader_manager:
        class: %scribe.file_uploader_manager.class%
        arguments: ["@service_container"]

    scribe.file_uploader.twig:
        class: %scribe.file_uploader.twig.class%
        arguments: ["@service_container"]
        tags:
            - { name: twig.extension }